name: flooz_wallet_replica
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.1
  equatable: ^2.0.5
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_emoji: ^2.4.0
  flutter_localizations:
    sdk: flutter
  form_inputs:
    path: packages/form_inputs
  formz: ^0.5.0+1
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  pin_code_fields: ^7.4.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
