name: app_ui
description: App UI component library
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  flutter:
    sdk: flutter
  flutter_emoji: ^2.4.0
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
